name: sentinel

volumes:
  sentinel:
  pg-data:
  mysql-data:
  mariadb-data:
  minio-data:

networks:
  sentinel:
    external: true

services:
  #  app:
  #    build: .
  #    networks:
  #      - sentinel
  #    volumes:
  #      - sentinel:/app/backups
  #    environment:
  #      BACKUP_DIRECTORY: /app/backups
  #    command: backup --type=mariadb --host=mariadb --port=3306 --password=root --database=nation --output=nation.sql --local-path=/app/backups

  mysql:
    image: docker.io/mysql:lts
    networks:
      - sentinel
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sentinel
      MYSQL_USER: sentinel
      MYSQL_PASSWORD: sentinel

  mariadb:
    image: docker.io/mariadb:11.2.4-jammy
    hostname: maria
    networks:
      - sentinel
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sentinel
      MYSQL_USER: sentinel
      MYSQL_PASSWORD: sentinel

  phpmyadmin:
    image: docker.io/phpmyadmin
    networks:
      - sentinel
    ports:
      - "8000:80"
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql

  pgsql:
    image: docker.io/postgres:16-alpine
    hostname: pgdb
    networks:
      - sentinel
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      PGPASSWORD: sentinel
      POSTGRES_DB: sentinel
      POSTGRES_USER: sentinel
      POSTGRES_PASSWORD: sentinel

  pgadmin:
    image: docker.io/dpage/pgadmin4:8
    networks:
      - sentinel
    ports:
      - "8001:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user@sentinel.io
      PGADMIN_DEFAULT_PASSWORD: secret1234

  minio:
    image: minio/minio:latest
    command: minio server /var/lib/minio/data --console-address ":9001"
    networks:
      - sentinel
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: sentinel
      MINIO_ROOT_PASSWORD: password
    volumes:
      - minio-data:/var/lib/minio/data



