import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * The sidebar is generated from the directory tree under `docs/`, not hand-maintained.
 *
 * This is deliberate. FR-033 forbids navigation entries that point at content which
 * does not exist yet, and content ships across five increments. An autogenerated
 * sidebar makes that requirement structurally impossible to violate: a page appears
 * in navigation exactly when its file appears, and never before.
 *
 * Section labels and ordering come from each directory's `_category_.json`.
 */
const sidebars: SidebarsConfig = {
  docs: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
};

export default sidebars;
